apiVersion: apps/v1
kind: Deployment
metadata:
  name: billboard-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billboard-client
  template:
    metadata:
      labels:
        app: billboard-client
    spec:
      containers:
      - image: asaikali/billboard-client:latest
        imagePullPolicy: Always
        name: billboard-client
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: 1000m
            memory: 1G
          limits:
            cpu: 1000m
            memory: 1G
