apiVersion: v1
kind: Service
metadata:
  labels:
    run: jvm
  name: jvm
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: jvm
  type: NodePort
