apiVersion: v1
kind: Service
metadata:
  labels:
    app: billlboard-client
  name: billboard-client
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: billboard-client
  type: NodePort
