apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: message-service

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - message-service/k8s/message-service.yaml

